version: '3.7'

services:
  node:
    build: .
    container_name: pc-node
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "${PORT}:${PORT}"

  postgres:
    image: postgres:11.6
    container_name: pc-postgres
    env_file:
      - .env
    ports:
      - "${PG_PORT}:${PG_PORT}"
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
