version: '3.7'

services:
  node0:
    container_name: node0-dev
    environment:
      NODE_ENV: 'development'
      MESSAGE: 'hello from instance 0'
    expose:
      - "${NODE_PORT}"
    command: npm run dev

  nginx0:
    volumes:
      - ./nginx/dev:/etc/nginx
    ports:
      - "${NGINX_PORT}:80"
