version: '3.7'

services:
  node0:
    build: ./api
    container_name: node0
    env_file: ./.env
    tty: true
    expose:
      - "${NODE_PORT}"
    depends_on:
      - postgres0
    volumes: 
      - ./api:/api

  postgres0:
    image: postgres:11.6
    container_name: postgres0
    restart: always
    environment:
      POSTGRES_PASSWORD: "${PG_PASS}"
    env_file: ./.env
    ports:
      - "${PG_PORT}:${PG_PORT}"
    volumes:
      - ./postgres/postgres.sh:/docker-entrypoint-initdb.d/init.sh
      - ./postgres/data:/var/lib/postgresql/data

  nginx0:
    image: nginx:latest
    tty: true
    container_name: nginx0
    env_file: ./.env
    links:
      - node0
    ports:
      - "${NGINX_PORT}:80"
    command: ["nginx", "-g", "daemon off;"]
