version: '3.7'

services:
  node0:
    build: ./api
    container_name: node0
    env_file: ./.env
    tty: true
    expose:
      - "${NODE_PORT}"
    depends_on:
      - postgres0
    volumes: 
      - ./api:/api
    networks:
      - my-network

  postgres0:
    image: postgres:11.6
    # build: ./postgres
    container_name: postgres0
    restart: always
    # tty: true
    environment:
      POSTGRES_PASSWORD: "${PG_PASS}"
    env_file: ./.env
    ports:
      - "${PG_PORT}:${PG_PORT}"
    volumes:
      - ./postgres/postgres.sh:/docker-entrypoint-initdb.d/init.sh
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - my-network

  nginx0:
    # image: nginx:latest
    build: ./nginx
    tty: true
    container_name: nginx0
    restart: always
    env_file: ./.env
    # links:
    #   - node0
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - my-network

networks:
  my-network:
