version: '3.7'

services:
  node:
    build: .
    container_name: my-node
    working_dir: /app
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "${PORT}:${PORT}"

  postgres:
    image: postgres:11.6
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "${PG_PASS}"
    ports:
      - "${PG_PORT}:${PG_PORT}"
    volumes:
      - ./init/10-postgres.sh:/docker-entrypoint-initdb.d/init.sh
