version: '3.7'

services:
  node:
    build: .
    container_name: project-node
    working_dir: /app
    depends_on:
      - postgres
    ports:
      - 3000:3000

  postgres:
    image: postgres:11.6
    container_name: project-postgres
    environment:
      POSTGRES_DB: project
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
